name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Utiliser 'master' au lieu de 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Spécifiez la version de Node.js (ajustez si nécessaire)

    - name: Install dependencies
      run: npm install  # Installe les dépendances (ajustez si vous n'utilisez pas npm)

    - name: Build
      run: npm run build  # Exécute la commande de build (ajustez si nécessaire)

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Répertoire contenant vos fichiers à déployer
