name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Changez à 'main' si votre branche principale est 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Utilisez la version de Node.js souhaitée
      
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build  # Assurez-vous que la commande 'build' existe dans package.json
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.KAITO_TOKEN }}
        publish_dir: ./build  # Changez ceci au répertoire généré par 'npm run build'
